 export let products = [
    {
      id: 1,
      title: "The Last of Us",
      price: 25000,
      description: " Es un videojuego de terror de acción y aventura de disparos en tercera persona" ,
      img: "https://res.cloudinary.com/drktnqgzs/image/upload/v1720047656/latest_swrehs.jpg",
      stock: 10,
      category: "PS3"
    },
    {
      id: 2,
      title: "Uncharted 2: El reino de los ladrones",
      price: 20000,
      stock: 10,
      description: "Es un videojuego de acción-aventura en tercera persona",
      category: "PS3",
      img: "https://res.cloudinary.com/drktnqgzs/image/upload/v1720047760/latest_e4mrrs.jpg",
    },
    {
      id: 3,
      title: "Uncharted 4: El desenlace del ladrón",
      price: 45000,
      stock: 10, 
      description: "Es un videojuego de acción-aventura en tercera persona",
      category: "PS4",
      img: "https://res.cloudinary.com/drktnqgzs/image/upload/v1720047797/latest_zkk6ia.jpg",
    },
    {
      id: 4,
      title: "God of War",
      price: 50000,
      stock: 10,
      description: "Es un videojuego de acción-aventura hack and slash en tercera persona",
      category: "PS4",
      img: "https://res.cloudinary.com/drktnqgzs/image/upload/v1720047920/latest_upgubj.png",
    },
    {
        id: 5,
        title: "Horizon Forbidden West",
        price: 75000,
        stock: 10,
        description: "Es un videojuego de rol de acción, aventura y mundo abierto",
        category: "PS5",
        img: "https://res.cloudinary.com/drktnqgzs/image/upload/v1720047974/latest_f19xuj.png",
      },
      {
        id: 6, 
        title: "God of War Ragnarök",
        price: 80000,
        stock:  10,
        description: "Es un videojuego de acción y aventura hack and slash en tercera persona",
        category: "PS5",
        img: "https://res.cloudinary.com/drktnqgzs/image/upload/v1720048083/latest_ia8eiz.png",
      },
    {
        id: 7,
        title: "Gears of War 3",
        price: 23000,
        stock: 10,
        description: "Es un videojuego de disparos en tercera persona, del género acción-aventura" ,
        category: "XBOX-360",
        img: "https://res.cloudinary.com/drktnqgzs/image/upload/v1720048102/latest_jzj4q3.png",
      },
      {
        id: 8,
        title: "Forza Motorsport 3",
        price: 21000,
        stock: 10,
        description: "Es un videojuego de carreras",
        category: "XBOX-360",
        img: "https://res.cloudinary.com/drktnqgzs/image/upload/v1720048164/450_1000_up4xca.webp",
      },
      {
        id: 9,
        title: "Sea of Thieves",
        price: 35000,
        stock: 10,
        description: "Es un videojuego de acción-aventura en primera persona",
        category: "XBOX-ONE",
        img: "https://res.cloudinary.com/drktnqgzs/image/upload/v1720048283/latest_yzvyv3.jpg",
      },
      {
        id: 10,
        title: "Forza Horizon 4",
        price: 38000,
        stock: 10,
        description: "Es un videojuego de carreras de mundo abierto, jugable en línea",
        category: "XBOX-ONE",
        img: "https://res.cloudinary.com/drktnqgzs/image/upload/v1720048321/forza-horizon-4-2018102103227_1_z7uad0.jpg",
      },
  ];